"""
Pydantic schemas for conversion analytics, pipeline metrics, and outcome learning.
"""

from pydantic import BaseModel, Field

from src.proposal.schemas import PitchAngle


class FunnelMetrics(BaseModel):
    """Conversion funnel and response rates across all application stages."""

    total_applications: int = Field(default=0, description="Total applications submitted")
    replied_count: int = Field(default=0, description="Applications that received a client reply")
    interview_count: int = Field(default=0, description="Applications that progressed to interview")
    negotiation_count: int = Field(default=0, description="Applications in active negotiation")
    won_count: int = Field(default=0, description="Contracts won")
    lost_count: int = Field(default=0, description="Proposals rejected / lost")
    active_count: int = Field(default=0, description="Applications currently in flight")

    # Percentage Rates (0.0 to 100.0)
    response_rate: float = Field(default=0.0, description="Percentage of applications replied to")
    interview_rate: float = Field(default=0.0, description="Percentage of applications interviewed")
    win_rate: float = Field(default=0.0, description="Overall win rate (Won / Total Applied)")
    close_rate: float = Field(
        default=0.0, description="Interview-to-close conversion rate (Won / Interviewed)"
    )

    # Velocity
    avg_time_to_reply_hours: float = Field(
        default=0.0, description="Average hours from application to first response"
    )
    avg_time_to_close_days: float = Field(
        default=0.0, description="Average days from application to contract win"
    )


class PitchAngleMetric(BaseModel):
    """Performance breakdown for a specific strategic proposal pitch angle."""

    pitch_angle: PitchAngle = Field(description="Strategic pitch angle")
    total_sent: int = Field(default=0, description="Proposals sent with this angle")
    replied: int = Field(default=0, description="Proposals that received responses")
    won: int = Field(default=0, description="Proposals won")
    win_rate: float = Field(default=0.0, description="Win rate percentage for this angle")
    avg_proposed_budget: float = Field(default=0.0, description="Average proposed rate")
    total_revenue: float = Field(default=0.0, description="Total revenue generated from this angle")


class SkillPerformanceMetric(BaseModel):
    """Historical win rate and revenue attribution by skill."""

    skill: str = Field(description="Normalized skill or technology name")
    applications_count: int = Field(default=0, description="Applications requiring this skill")
    wins_count: int = Field(default=0, description="Projects won with this skill")
    win_rate: float = Field(default=0.0, description="Win rate percentage for this skill")
    total_revenue: float = Field(default=0.0, description="Total revenue generated")


class RevenueMetrics(BaseModel):
    """Financial tracking, deal sizes, and pipeline value."""

    total_pipeline_value: float = Field(default=0.0, description="Sum of proposed active budgets")
    realized_revenue: float = Field(default=0.0, description="Total revenue from won contracts")
    average_deal_size: float = Field(
        default=0.0, description="Average contract value of won projects"
    )
    highest_deal_value: float = Field(default=0.0, description="Largest single contract won")
    currency: str = Field(default="USD", description="Base reporting currency")


class CalibratedWinModifier(BaseModel):
    """Empirical calibration multiplier learned from historical outcomes."""

    feature_name: str = Field(description="Name of skill, source, or pitch angle")
    feature_type: str = Field(description="Category (SKILL, PITCH_ANGLE, SOURCE)")
    sample_size: int = Field(description="Number of historical applications evaluated")
    empirical_win_rate: float = Field(description="Actual observed win rate percentage")
    multiplier: float = Field(
        description="Scoring multiplier relative to baseline (e.g. 1.2x boost or 0.8x penalty)"
    )


class LearningInsights(BaseModel):
    """Empirical takeaways and optimization recommendations generated by the learning engine."""

    best_pitch_angle: PitchAngle | None = Field(
        default=None, description="Most effective pitch angle"
    )
    highest_converting_skills: list[str] = Field(
        default_factory=list, description="Top skills by win rate"
    )
    top_revenue_skills: list[str] = Field(
        default_factory=list, description="Top skills by realized revenue"
    )
    calibrated_modifiers: list[CalibratedWinModifier] = Field(
        default_factory=list, description="Learned win probability adjustments"
    )
    recommendations: list[str] = Field(
        default_factory=list, description="Actionable strategy suggestions"
    )
